### ISSUE TITLE
Ownership Change

### ISSUE THREAD

**Issue by coolGi69** [vadis365/Uppers#16]
Hi, I'm just wondering if you are still here?

I really enjoy using the Uppers mod as it makes Redstone a lot easier. But I've noticed that you aren't here any more (at least on GitHub) due to your last activity on GitHub being on January the 21st.

If it is alright, may I fork it, and release updates to the mod to newer versions, and Fabric and release those onto Modrinth?\
Don't worry, I'll rebrand the mod slightly (probably to Uppers Modernised).\
So far, I have got my own [GitHub repo of a 1.20.1 version of this mod](https://github.com/coolGi2007/Uppers-modernised/tree/1.20.1), and want to probably post it somewhere public.

Some of the other works I've done is being one of the lead developers of [Distant Horizons](https://gitlab.com/jeseibel/minecraft-lod-mod) which you can view at [Curseforge](https://www.curseforge.com/minecraft/mc-mods/distant-horizons) and [Modrinth](https://modrinth.com/mod/distanthorizons), so I have quite a bit of experience in modding.
If you'd like to view my Git profile, it's at: https://gitlab.com/coolGi

Hope to hear back from you soon,

Thanks,
coolGi

**Comment by vadis365** [comment]
Um, I'm still making this mod - and have every intention of continuing it.
I actually work using the git client in some other repos which don't show activity here - so I am actually active still, you are incorrect in assuming I'm 'gone'. I can't stop you making an alternative mod ofc, but it is a bit premature to jump on this mod for a remake, considering it is available in 1.19 and only one version behind the latest.
If you want to PR the project to keep it up to date (if you can't wait for me) then you could do that?
Other than that I don't know what else to say.
Cheers,
Me.

**Comment by vadis365** [comment]
Just looked at your repo, I mean - you could have easily made a PR with those changes (without removing my name!)

**Comment by vadis365** [comment]
I am on discord as vadis365 (easiest place to talk to me) if you would like to continue this conversation.
